project_id = "xuphjyjabsnduukzfevz"

[functions.send-contact-notification]
verify_jwt = false

[functions.send-quote-notification]
verify_jwt = false

[functions.send-appointment-notification]
verify_jwt = false
