project_id = "xuphjyjabsnduukzfevz"

[functions.send-contact-notification]
verify_jwt = false

[functions.send-quote-notification]
verify_jwt = false

[functions.send-appointment-notification]
verify_jwt = false

[functions.send-consultation-notification]
verify_jwt = false

[functions.review-consultation-payment]
verify_jwt = false

