// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-properties.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/data/properties.ts
var properties = [
  {
    id: "villa-gombe-piscine",
    title: "Villa Moderne avec Piscine",
    location: "Gombe, Kinshasa",
    price: "350 000 $",
    type: "Vente",
    beds: 5,
    baths: 3,
    area: "450 m\xB2",
    description: "Magnifique villa contemporaine avec piscine, jardin paysager et finitions haut de gamme."
  },
  {
    id: "appartement-ngaliema-meuble",
    title: "Appartement Meubl\xE9 3 Chambres",
    location: "Ngaliema, Kinshasa",
    price: "1 500 $/mois",
    type: "Location",
    beds: 3,
    baths: 2,
    area: "150 m\xB2",
    description: "Appartement enti\xE8rement meubl\xE9 avec vue d\xE9gag\xE9e, parking s\xE9curis\xE9 et gardiennage 24h/24."
  },
  {
    id: "bureau-gombe-commercial",
    title: "Bureau Commercial",
    location: "Gombe, Kinshasa",
    price: "2 800 $/mois",
    type: "Location",
    beds: 0,
    baths: 2,
    area: "200 m\xB2",
    description: "Espace commercial moderne avec fa\xE7ade vitr\xE9e, id\xE9al pour bureaux ou showroom."
  },
  {
    id: "duplex-bandalungwa",
    title: "Maison Duplex avec Parking",
    location: "Bandalungwa, Kinshasa",
    price: "180 000 $",
    type: "Vente",
    beds: 4,
    baths: 2,
    area: "280 m\xB2",
    description: "Duplex spacieux avec terrasse, garage et quartier r\xE9sidentiel calme."
  },
  {
    id: "penthouse-gombe-panoramique",
    title: "Penthouse Vue Panoramique",
    location: "Gombe, Kinshasa",
    price: "4 500 $/mois",
    type: "Location",
    beds: 3,
    baths: 2,
    area: "220 m\xB2",
    description: "Penthouse de luxe au dernier \xE9tage avec vue panoramique sur la ville."
  },
  {
    id: "terrain-mont-ngafula",
    title: "Terrain Constructible 800 m\xB2",
    location: "Mont-Ngafula, Kinshasa",
    price: "95 000 $",
    type: "Vente",
    beds: 0,
    baths: 0,
    area: "800 m\xB2",
    description: "Terrain viabilis\xE9 dans une zone r\xE9sidentielle en pleine expansion."
  }
];

// src/lib/mcp/tools/list-properties.ts
var list_properties_default = defineTool({
  name: "list_properties",
  title: "Lister les biens immobiliers",
  description: "Retourne les biens immobiliers Gestimmo Digital \xE0 Kinshasa (villas, appartements, bureaux, terrains). Filtres optionnels par type (Vente/Location) et par commune.",
  inputSchema: {
    type: z.enum(["Vente", "Location"]).optional().describe("Filtrer par type: Vente ou Location."),
    location: z.string().optional().describe("Filtrer par commune de Kinshasa (ex: Gombe, Ngaliema).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ type, location }) => {
    const loc = location?.toLowerCase();
    const results = properties.filter(
      (p) => (!type || p.type === type) && (!loc || p.location.toLowerCase().includes(loc))
    );
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { properties: results, count: results.length }
    };
  }
});

// src/lib/mcp/tools/get-property.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_property_default = defineTool2({
  name: "get_property",
  title: "D\xE9tails d'un bien",
  description: "Retourne les d\xE9tails complets d'un bien immobilier par son id.",
  inputSchema: {
    id: z2.string().min(1).describe("Identifiant du bien (ex: villa-gombe-piscine).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const found = properties.find((p) => p.id === id);
    if (!found) {
      return {
        content: [{ type: "text", text: `Aucun bien trouv\xE9 pour l'id "${id}".` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(found, null, 2) }],
      structuredContent: { property: found }
    };
  }
});

// src/lib/mcp/tools/get-agency-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_agency_info_default = defineTool3({
  name: "get_agency_info",
  title: "Informations sur l'agence",
  description: "Retourne les informations g\xE9n\xE9rales sur Gestimmo Digital : services, coordonn\xE9es, zone d'activit\xE9.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      nom: "Gestimmo Digital",
      responsable: "Benedit",
      ville: "Kinshasa, R\xE9publique D\xE9mocratique du Congo",
      email: "contact.gestimmodigital@gmail.com",
      whatsapp: "+243 82 97 91 356",
      services: [
        "Vente et location de biens immobiliers \xE0 Kinshasa",
        "Gestion locative",
        "Marketing digital (r\xE9seaux sociaux, Facebook & Google Ads)",
        "Branding et acquisition de clients"
      ],
      site: "https://gestimmodigital.lovable.app"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/send-contact-message.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { createClient } from "npm:@supabase/supabase-js@^2.105.4";
var send_contact_message_default = defineTool4({
  name: "send_contact_message",
  title: "Envoyer un message de contact",
  description: "Envoie un message via le formulaire de contact Gestimmo Digital. Les messages re\xE7us ne sont PAS lisibles via MCP.",
  inputSchema: {
    name: z3.string().trim().min(1).max(100).describe("Nom complet de la personne."),
    email: z3.string().trim().email().max(255).describe("Adresse email de contact."),
    phone: z3.string().trim().max(30).optional().describe("T\xE9l\xE9phone (optionnel)."),
    message: z3.string().trim().min(1).max(2e3).describe("Contenu du message.")
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ name, email, phone, message }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY;
    if (!url || !key) {
      return {
        content: [{ type: "text", text: "Backend non configur\xE9." }],
        isError: true
      };
    }
    const supabase = createClient(url, key, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { error } = await supabase.from("contact_messages").insert({
      name,
      email,
      phone: phone ?? null,
      message
    });
    if (error) {
      return {
        content: [{ type: "text", text: `Erreur: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: "Message envoy\xE9 avec succ\xE8s. L'\xE9quipe Gestimmo Digital vous r\xE9pondra rapidement."
        }
      ],
      structuredContent: { ok: true }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "gestimmo-digital-mcp",
  title: "Gestimmo Digital MCP",
  version: "0.1.0",
  instructions: "Outils publics de Gestimmo Digital, agence immobili\xE8re et marketing digital \xE0 Kinshasa. Utilisez `list_properties` et `get_property` pour explorer le catalogue de biens, `get_agency_info` pour les coordonn\xE9es et services, et `send_contact_message` pour transmettre une demande via le formulaire de contact.",
  tools: [
    list_properties_default,
    get_property_default,
    get_agency_info_default,
    send_contact_message_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
